name: flutter_local_storage_examples
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter_secure_storage: ^9.2.4
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
